import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Jura } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({ 
  subsets: ['latin', 'cyrillic'],
  variable: '--font-inter', // CSS-переменная
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jura = Jura({ 
  subsets: ['latin', 'cyrillic'], // Поддерживаемые языки
  weight: ['300', '400', '500', '600', '700'],  // Нужные начертания
  variable: '--font-jura',        // Опционально: для CSS-переменной
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jura.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
